name: Vuild and deploy static

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: "16.13.1"
      - name: Install deps
        run: npm ci
        working-directory: ./frontend
      - name: Build static
        run: npm run build
        working-directory: ./frontend
      - name: Sync static
        uses: garygrossgarten/github-action-scp@release
        with:
          local: frontend/dist
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
