name: Vuild and deploy static

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync static
        uses: garygrossgarten/github-action-scp@release
        with:
          local: frontend
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
      - name: Build static
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd ${{ secrets.PATH }} && npm i && npm run build
